server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alanredsheep/springclouddemo.git
          search-paths: config
          username: {username}
          password: {password}
      label: master